# Śmierć tylko od gracza zabiera życie?
player-death-only: false

# Życia na start
default-lives: 5

# Maksymalna liczba żyć
max-lives: 5

# Życia po odbanowaniu
lives-after-ban: 3

# Czas bana w godzinach
ban-duration-hours: 48

# Powód bana
ban-reason: "Straciłeś wszystkie życia! Wróć za 48 godzin."
