name: LifeSystem
version: 1.1.0
main: pl.lifesystem.LifeSystem
api-version: '1.21'
author: yogurt
description: System żyć z craftingiem i banem.

commands:
  lifesystem:
    description: Główna komenda systemu żyć.
    aliases: [ls, life]
